version: "2"
services:
  broker:
    build:
      context: ../../message_broker
    image: example/broker

  producer:
    build:
      context: ../../nodejs_producer
    image: example/producer

  consumer:
    build:
      context: ../../elixir_consumer
    image: example/consumer
